[mgr]
prepend_keymap = [
  { on = "<C-h>", run = "help", desc = "help" },
  { on = "H", run = "noop" },
  { on = "h", run = "noop" },
  { on = "k", run = "noop" },
  { on = "K", run = "noop" },
  { on = "j", run = "noop" },
  { on = "J", run = "noop" },
  { on = "l", run = "noop" },
  { on = "L", run = "noop" },
  { on = "<C-[>", run = "noop" },
  { on = "<C-u>", run = "noop" },
  { on = "<C-u>", run = "noop" },
  { on = "<C-d>", run = "noop" },
  { on = "<C-b>", run = "noop" },
  { on = "<C-f>", run = "noop" },
  { on = "<S-PageUp>", run = "noop" },
  { on = "<S-PageDown>", run = "noop" },
  { on = "<PageUp>", run = "arrow -50%" },
  { on = "<PageDown>", run = "arrow +50%" },
  { on = "<Space>", run = "toggle" },
  { on = "<Tab>", run = "noop" },
  { on = "i", run = "spot", desc = "info" },
  { on = ";", run = "noop" },
  { on = ":", run = "noop" },
  { on = "s", run = "search --via=rg", desc = "search" },
  { on = "S", run = "noop" },
  { on = "z", run = "plugin zoxide", desc = "zoxide" },
  { on = "Z", run = "noop" },
  { on = "?", run = "noop" },
  { on = "~", run = "noop" },
  { on = "<F1>", run = "noop" },
  { on = "<C-Down>", run = "seek +5", desc = "preview scroll down" },
  { on = "<C-Up>", run = "seek -5", desc = "preview scroll up" },
]
append_keymap = [
  { on = [
    "g",
    "p",
  ], run = "cd ~/programming", desc = "Go ~/programming" },
]
